#ifndef KDECONNECT_PLUGIN_BATTERY_DEBUG_H
#define KDECONNECT_PLUGIN_BATTERY_DEBUG_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(KDECONNECT_PLUGIN_BATTERY)

#endif // KDECONNECT_PLUGIN_BATTERY_DEBUG_H
